import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/business/components/navigation/header";

const buenoMono = localFont({
  src: "./fonts/Bueno.woff",
  variable: "--font-bueno-mono",
  weight: "400"
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative ${buenoMono.variable} ${inter.variable} min-h-svh w-screen overflow-y-auto`}>
        <Header />
        <main className="2xl:container">{children}</main>
      </body>
    </html>
  );
}
