import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/business/navigation/components/header";
import { Footer } from "@/business/navigation/components/footer";

const buenoMono = localFont({
  src: "./fonts/Bueno.woff",
  variable: "--font-bueno-mono",
  weight: "400"
});

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter"
});

const twemoji = localFont({
  src: "./fonts/Twemoji.Mozilla.ttf",
  display: "swap",
  variable: "--font-twemoji"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative ${buenoMono.variable} ${inter.variable} ${twemoji.variable} min-h-svh w-screen overflow-y-auto`}
      >
        <Header />
        <main className="2xl:container sm:pt-20">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
